name: dart_ast_viewer
description: dart_ast_viewer

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  analyzer: ^4.2.0
  flutter_hooks: ^0.18.5+1
  graphview: ^1.1.1
  path: ^1.8.2

flutter:
  uses-material-design: true

